FROM spark-base

COPY scripts/start-worker.sh /

ENV SPARK_MASTER spark://spark-master:7077
ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /var/log/spark
EXPOSE 8081

ENTRYPOINT ["/bin/bash", "/start-worker.sh"]