version: "3.7"
services:
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"

  spark-worker:
    image: spark-worker
    depends_on:
      - spark-master
    env_file: ./env/spark-worker.sh
