version: "3.7"
services:
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
  
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: ./env/spark-worker.sh
  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    env_file: ./env/spark-worker.sh
