FROM spark-base

COPY scripts/start-master.sh /

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /var/log/spark

EXPOSE 8080 7077 6066

ENTRYPOINT ["/bin/bash", "/start-master.sh"]
#CMD ["/bin/bash", "/start-master.sh"]
